apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "foreman.fullname" . }}
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: server
data:
  database.yml: |-
    production:
      adapter: postgresql
      host: {{ template "foreman.fullname" . }}-postgres
      port: {{ .Values.postgres.port }}
      database: {{ .Values.postgres.dbName }}
      username: {{ .Values.postgres.user }}
      password: {{ .Values.postgres.password }}
      pool: 5
  foreman-nginx.conf: |-
    server {
        listen {{ .Values.foreman.service.internalPort }};
        server_name {{ .Values.foreman.serverName }};
        passenger_app_root /home/app/foreman/;
        root /home/app/foreman/public/;
        passenger_enabled on;
        passenger_user app;
    
        # Specify a Ruby version:
        passenger_ruby /usr/bin/ruby2.3;
    }
