apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "foreman.fullname" . }}
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: server
data:
  database.yml: |-
    production:
      adapter: postgresql
      host: {{ template "foreman.fullname" . }}-postgres
      port: {{ .Values.postgres.service.externalPort }}
      database: {{ .Values.postgres.dbName }}
      username: {{ .Values.postgres.user }}
      password: {{ .Values.postgres.password }}
      pool: 5
    test:
      adapter: postgresql
      host: {{ template "foreman.fullname" . }}-postgres
      port: {{ .Values.postgres.service.externalPort }}
      database: {{ .Values.postgres.dbName }}
      username: {{ .Values.postgres.user }}
      password: {{ .Values.postgres.password }}
    development:
      adapter: postgresql
      host: {{ template "foreman.fullname" . }}-postgres
      port: {{ .Values.postgres.service.externalPort }}
      database: {{ .Values.postgres.dbName }}
      username: {{ .Values.postgres.user }}
      password: {{ .Values.postgres.password }}
  foreman-nginx.conf: |-
    server {
        listen {{ .Values.foreman.service.internalPort }};
        listen {{ .Values.foreman.service.internalPortSSL }} ssl;
        ssl_certificate {{ .Values.foreman.certName }};
        ssl_certificate_key {{ .Values.foreman.privkeyName }};
        server_name {{ .Values.foreman.serverName }};
        root /home/app/foreman/public;
        passenger_enabled on;
        passenger_user app;
        passenger_max_request_queue_size 500;

        # Specify a Ruby version:
        passenger_ruby /usr/bin/ruby2.3;

        location ~ ^/(assets|images|javascripts|stylesheets|swfs|system)/ {
          gzip_static on;
          expires     max;
          add_header  Cache-Control public;
          add_header  Last-Modified "";
          add_header  ETag "";
          break;
        }

        location /nginx_status {
          stub_status on;
          access_log   off;
          allow 127.0.0.1;
          deny all;
        }
    }
  settings.yaml: |-
    :unattended: true
    :login: true
    :require_ssl: false
    :locations_enabled: false
    :organizations_enabled: false
    :support_jsonp: false
{{ if .Values.puppet.enabled }}
    :puppetconfdir: /var/lib/puppet/conf
    :puppetvardir: /var/lib/puppet
    :puppetssldir: /var/lib/puppet/ssl

{{- end }}
    :mark_translated: false
    :webpack_dev_server: true
    :webpack_dev_server_https: false

    :domain: {{ .Values.foreman.domainName }}
    :fqdn: {{ .Values.foreman.serverName }}

    :ssl_certificate: {{ .Values.foreman.certName }}
    :ssl_ca_file: {{ .Values.foreman.caName }}
    :ssl_priv_key: {{ .Values.foreman.privkeyName }}

    :idle_timeout: {{ .Values.foreman.idleTimeout }}
    :entries_per_page: {{ .Values.foreman.entriesPerPage }}
  nginx.conf: |-
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;
    daemon off;
    include /etc/nginx/main.d/*.conf;
    events {
        worker_connections 768;
    }
    http {
        # Basic Settings
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # SSL Settings
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        # Logging Settings
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # Gzip Settings
        gzip on;
        gzip_disable "msie6";
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        # Phusion Passenger config
        include /etc/nginx/passenger.conf;

        # Virtual Host Configs

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
    }
  passenger.conf: |-
    passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
    passenger_ruby /usr/bin/passenger_free_ruby;
    passenger_max_pool_size 20;
