apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "foreman.fullname" . }}
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: server
data:
  database.yml: |-
    production:
      adapter: postgresql
      host: {{ template "foreman.fullname" . }}-postgres
      port: {{ .Values.postgres.service.externalPort }}
      database: {{ .Values.postgres.dbName }}
      username: {{ .Values.postgres.user }}
      password: {{ .Values.postgres.password }}
      pool: 5
    test:
      adapter: postgresql
      host: {{ template "foreman.fullname" . }}-postgres
      port: {{ .Values.postgres.service.externalPort }}
      database: {{ .Values.postgres.dbName }}
      username: {{ .Values.postgres.user }}
      password: {{ .Values.postgres.password }}
    development:
      adapter: postgresql
      host: {{ template "foreman.fullname" . }}-postgres
      port: {{ .Values.postgres.service.externalPort }}
      database: {{ .Values.postgres.dbName }}
      username: {{ .Values.postgres.user }}
      password: {{ .Values.postgres.password }}
  foreman-nginx.conf: |-
    server {
        listen {{ .Values.foreman.service.internalPort }};
        server_name {{ .Values.foreman.serverName }};
        root /home/app/foreman/public;
        passenger_enabled on;
        passenger_user app;

        # Specify a Ruby version:
        passenger_ruby /usr/bin/ruby2.3;

        location ~ ^/(assets|images|javascripts|stylesheets|swfs|system)/ {
          gzip_static on;
          expires     max;
          add_header  Cache-Control public;
          add_header  Last-Modified "";
          add_header  ETag "";
          break;
        }

        location /nginx_status {
          stub_status on;
          access_log   off;
          allow 127.0.0.1;
          deny all;
        }
    }
  settings.yaml: |-
    :unattended: true
    :login: true
    :require_ssl: false
    :locations_enabled: false
    :organizations_enabled: false
    :support_jsonp: false
{{ if .Values.puppet.enabled }}
    :puppetconfdir: /var/lib/puppet/conf
    :puppetvardir: /var/lib/puppet
    :puppetssldir: /var/lib/puppet/ssl
    :trusted_puppetmaster_hosts: [*]
{{- end }}
    :mark_translated: false
    :webpack_dev_server: true
    :webpack_dev_server_https: false

    :domain: {{ .Values.foreman.domainName }}
    :fqdn: {{ .Values.foreman.serverName }}

    :ssl_certificate: {{ .Values.foreman.certName }}
    :ssl_ca_file: {{ .Values.foreman.caName }}
    :ssl_priv_key: {{ .Values.foreman.privkeyName }}

    :idle_timeout: {{ .Values.foreman.idleTimeout }}
    :entries_per_page: {{ .Values.foreman.entriesPerPage }}
