apiVersion: v1
kind: Service
metadata:
  name: {{ template "foreman.fullname" . }}-ssl
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.foreman.service.type }}
  ports:
    - port: {{ .Values.foreman.service.externalPortSSL }}
      targetPort: {{ .Values.foreman.service.internalPortSSL }}
      protocol: TCP
      name: https
  selector:
    app: {{ template "foreman.name" . }}
    release: {{ .Release.Name }}
    component: server
