apiVersion: v1
kind: Service
metadata:
  name: {{ template "foreman.fullname" . }}
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.foreman.service.type }}
  ports:
    - port: {{ .Values.foreman.service.externalPort }}
      targetPort: {{ .Values.foreman.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "foreman.name" . }}
    release: {{ .Release.Name }}
    component: server
