apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "foreman.fullname" . }}-encryptionkey
data: 
  encryption_key.rb: {{ .Values.foreman.encryptionKey }}
  local_secret_token.rb: {{ .Values.foreman.localSecretToken }}
