{{ if .Values.puppet.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "foreman.fullname" . }}-puppet
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.volume.size }}
  storageClassName: {{ .Values.volume.class }}
{{ if eq .Values.volume.class "efs" }}
  selector:
    matchLabels:
      app: 'foreman-puppet'
{{- end }}
{{- end }}
