apiVersion: v1
kind: Service
metadata:
  name: puppet-proxy
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: puppet-smart-proxy
spec:
  type: {{ .Values.puppet.proxy.service.type }}
  ports:
    - port: {{ .Values.puppet.proxy.service.nonSSL.externalPort }}
      targetPort: {{ .Values.puppet.proxy.service.nonSSL.internalPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.puppet.proxy.service.SSL.externalPort }}
      targetPort: {{ .Values.puppet.proxy.service.SSL.internalPort }}
      protocol: TCP
      name: https
  selector:
    app: {{ template "foreman.name" . }}
    release: {{ .Release.Name }}
    component: puppet
