{{ if .Values.puppet.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "foreman.fullname" . }}-puppetboard
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: puppetboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "foreman.name" . }}
      release: {{ .Release.Name }}
      component: puppetboard
  template:
    metadata:
      labels:
        app: {{ template "foreman.name" . }}
        release: {{ .Release.Name }}
        component: puppetboard
    spec:
      containers:
        - name: puppetboard
          image: "{{ .Values.puppetboard.image.repository }}:{{ .Values.puppetboard.image.tag }}"
          imagePullPolicy: {{ .Values.puppetboard.image.pullPolicy }}
          ports:
            - name: puppetboard
              containerPort: {{ .Values.puppetboard.service.internalPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              port: puppetboard
              path: /
              scheme: HTTP
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 10
          env:
            - name: PUPPETDB_HOST
              value: {{ template "foreman.fullname" . }}-puppetdb
            - name: PUPPETDB_PORT
              value: {{ .Values.puppetdb.service.SSL.externalPort }}
            - name: PUPPETDB_SSL_VERIFY
              value: {{ .Values.puppetdb.caPath | quote }}
            - name: PUPPETDB_KEY
              value: {{ .Values.puppetdb.privkeyPath | quote }}
            - name: PUPPETDB_CERT
              value: {{ .Values.puppetdb.caPath | quote }}
          volumeMounts:
            - mountPath: /var/lib/puppet
              name: puppet
          resources:
{{ toYaml .Values.puppetboard.resources | indent 12 }}
      volumes:
        - name: puppet
          persistentVolumeClaim:
            claimName: {{ template "foreman.fullname" . }}-puppet
        - name: puppetconfig
          configMap:
            name: {{ template "foreman.fullname" . }}-puppet
{{- end}}
