apiVersion: v1
kind: Service
metadata:
  name: {{ template "foreman.fullname" . }}-puppetdb-ssl
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: puppetdb
spec:
  type: {{ .Values.puppetdb.service.type }}
  ports:
    - port: {{ .Values.puppetdb.service.externalPortSSL }}
      targetPort: {{ .Values.puppetdb.service.internalPortSSL }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "foreman.name" . }}
    release: {{ .Release.Name }}
    component: puppetdb
