apiVersion: v1
kind: Service
metadata:
  name: {{ template "foreman.fullname" . }}-puppetdb
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: puppetdb
{{- with .Values.puppetdb.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.puppetdb.service.type }}
  ports:
    - port: {{ .Values.puppetdb.service.nonSSL.externalPort }}
      targetPort: {{ .Values.puppetdb.service.nonSSL.internalPort }}
{{- if .Values.puppetdb.service.nonSSL.nodePort }}
      nodePort: {{ .Values.puppetdb.service.nonSSL.nodePort }}
{{- end }}
      protocol: TCP
      name: http
    - port: {{ .Values.puppetdb.service.SSL.externalPort }}
      targetPort: {{ .Values.puppetdb.service.SSL.internalPort }}
      protocol: TCP
      name: https
{{- if .Values.puppetdb.service.SSL.nodePort }}
      nodePort: {{ .Values.puppetdb.service.SSL.nodePort }}
{{- end }}
  selector:
    app: {{ template "foreman.name" . }}
    release: {{ .Release.Name }}
    component: puppetdb
