{{ if .Values.puppet.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: puppetboard
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: puppetboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ template "foreman.name" . }}
      release: {{ .Release.Name }}
      component: puppetboard
  template:
    metadata:
      labels:
        app: {{ template "foreman.name" . }}
        release: {{ .Release.Name }}
        component: puppetboard
    spec:
      containers:
        - name: puppetboard
          image: "{{ .Values.puppetboard.image.repository }}:{{ .Values.puppetboard.image.tag }}"
          imagePullPolicy: {{ .Values.puppetboard.image.pullPolicy }}
          ports:
            - name: puppetboard
              containerPort: {{ .Values.puppetboard.service.internalPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              port: puppetboard
              path: /
              scheme: HTTP
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /var/lib/puppet
              name: puppet
            - mountPath: /var/www/puppetboard/settings.py
              name: config
              subPath: settings.py
          resources:
{{ toYaml .Values.puppetboard.resources | indent 12 }}
      volumes:
        - name: puppet
          persistentVolumeClaim:
            claimName: {{ template "foreman.fullname" . }}-puppet
        - name: config
          configMap:
            name: puppetboard
{{- end}}
