apiVersion: v1
kind: Service
metadata:
  name: puppet
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: puppet
spec:
  type: {{ .Values.puppet.service.type }}
  ports:
    - port: {{ .Values.puppet.service.externalPort }}
      targetPort: {{ .Values.puppet.service.internalPort }}
      nodePort: {{ .Values.puppet.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "foreman.name" . }}
    release: {{ .Release.Name }}
    component: puppet
