{{- if .Values.puppet.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: puppetboard
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: puppetboard
spec:
  type: {{ .Values.puppetboard.service.type }}
  ports:
    - port: {{ .Values.puppetboard.service.externalPort }}
      targetPort: {{ .Values.puppetboard.service.internalPort }}
      nodePort: {{ .Values.puppetboard.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "foreman.name" . }}
    release: {{ .Release.Name }}
    component: puppetboard
{{- end }}
