{{ if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "foreman.fullname" . }}-postgres
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.postgres.volume.size }}
    storageClassName: {{ .Values.postgres.volume.class }}
{{ if eq .Values.postgres.volume.class "efs" }}
    selector:
      matchLabels:
        app: 'foreman'
{{- end }}
{{- end }}
