apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "foreman.fullname" . }}-smartproxy
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: smartproxy
data:
  settings.yaml: |-
    ---
    :settings_directory: "/etc/foreman-proxy/settings.d"
    :trusted_hosts: []
    :daemon: true
    :bind_host: localhost
    :http_port: 8000
